### ISSUE TITLE
fails to build with polymer cli

### ISSUE THREAD

**Issue by joeblew99** [PolymerElements/marked-element#37]
node: 6.3.1.
polymer cli: 0.13.0

When using "marked-element" within the standard app template that the polymer cli generates, a page with this element will cause the build to output an error. When "marked-element" is removed there is no error.

```
polymer build
(node:35377) fs: re-evaluating native module sources is not supported. If you are using the graceful-fs module, please update it to a more recent version.
info:    Building application...
info:    Generating build/unbundled...
info:    Generating build/bundled...
warn:    Unable to optimize .js file /Users/apple/workspace/go/src/bitbucket.org/gedw99/md/public-website/public/src/my-view5.html_script_0.js 
{ err: 
   { message: 'SyntaxError: Unexpected character \'#\'',
     filename: 0,
     line: 2,
     col: 8,
     pos: 9,
     stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1545:18)\n    at js_error (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1553:11)\n    at parse_error (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1677:9)\n    at Object.next_token [as input] (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:1946:9)\n    at next (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2075:25)\n    at Object.parse (eval at <anonymous> (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:28:1), <anonymous>:2061:15)\n    at addFile (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:69:33)\n    at /Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:77:17\n    at Array.forEach (native)\n    at Object.exports.minify (/Users/apple/.nvm/versions/node/v6.3.1/lib/node_modules/polymer-cli/node_modules/uglify-js/tools/node.js:75:26)' } }
info:    Build complete!

```

test page:

``````
<link rel="import" href="../bower_components/polymer/polymer.html">

<link rel="import" href="../bower_components/marked-element/marked-element.html">

<dom-module id="my-view5">

  <template>

    <style>
      :host {
        display: block;
        padding: 10px;
      }

      .card {
        box-shadow: 0 2px 2px 0 rgba(0, 0, 0, 0.14), 0 1px 5px 0 rgba(0, 0, 0, 0.12), 0 3px 1px -2px rgba(0, 0, 0, 0.2);
        padding: 16px;
        margin: 24px;
        border-radius: 5px;
        background-color: #fff;
        color: #757575;
      }

      .circle {
        display: inline-block;
        height: 64px;
        width: 64px;
        border-radius: 50%;
        background: #ddd;
        line-height: 64px;
        font-size: 30px;
        color: #555;
        text-align: center;
      }

      h1 {
        font-size: 22px;
        margin: 16px 0;
        color: #212121;
      }
    </style>

    <div class="card">
      <div class="circle">5</div>
      <h1>View Five.</h1>
      <p>Modus commodo minimum eum te, vero utinam assueverit per eu.</p>
      <p>Ea duis bonorum nec, falli paulo aliquid ei eum.Has at minim mucius aliquam, est id tempor laoreet.Pro saepe pertinax
        ei, ad pri animal labores suscipiantur.</p>
    </div>


    <marked-element>
      <div class="markdown-html"></div>
      <script type="text/markdown">
        # Check out my markdown!

        ## h2

        ### h3
        - dd
          - df

        We can even embed elements without fear of the HTML parser mucking up their
        textual representation:

        ```html
        <awesome-sauce>
          <div>Oops, I'm about to forget to close this div.
        </awesome-sauce>
        ```
      </script>
    </marked-element>



  </template>

  <script>

    Polymer({

      is: 'my-view5'

    });

  </script>

</dom-module>
``````

**Comment by FredKSchott** [comment]
That output looks scary, but it is just a warning. Your app will still continue to build, just marked-element will not have been minified.

Still, we should look into what uglify doesn't like about marked-element. Possibly the long comment in marked-element.html?

**Comment by 43081j** [comment]
@FredKSchott FYI this is because polymer-build will take any script tag regardless of type and pass it through as `.js` ([here](https://github.com/Polymer/polymer-build/blob/master/src/polymer-project.ts#L189)).

This is due to unknown types defaulting to `js` ([this map](https://github.com/Polymer/polymer-build/blob/master/src/polymer-project.ts#L27)), [here](https://github.com/Polymer/polymer-build/blob/master/src/polymer-project.ts#L216).

I don't think it is uglify's fault as it expects you to be passing JS, which we are not.

I made an issue [here](https://github.com/Polymer/polymer-build/issues/55).

**Comment by joeblew99** [comment]
@FredKSchott 

You mentioned that the bug does not matter because its just errors to screen, but the build still works.
That is not what i am experiencing. You should try..
Today i tried it again, and below is my findings.

polymer server WORKS
polymer build WORKS; with all the errors spat out about uglify having a bad day..
polymer serve build/bundled FAILS. Cant even server index.html.
polymer server build/unbundled WORKS.

my Env:
polymer cli v 1.6
node 1.6.3
osx

**Comment by FredKSchott** [comment]
@43081j @joeblew99 thanks for digging into this, just created a PR to fix in polymer-build. 

It _should_ just be warning and still building properly, but it sounds like it's not. I'll have to dig into that a bit more as well.

**Comment by joeblew99** [comment]
@FredKSchott thanks for picking this up again.

let me know if you need any more info...

**Comment by stramel** [comment]
Can this be closed?

**Comment by stramel** [comment]
@FredKSchott Do you want to close this since your fix was merged last october?
